from django.urls import path

from .admin_api import (
    AdminBookChaptersAPIView,
    AdminBookDetailAPIView,
    AdminBookListCreateAPIView,
    AdminChapterDetailAPIView,
    AdminProjectDetailAPIView,
    AdminProjectListAPIView,
    AdminReportDetailAPIView,
    AdminReportsAPIView,
    AdminStatsAPIView,
    AdminUserDetailAPIView,
    AdminUserListAPIView,
)
from .views import (
    ConnectionAPIView,
    LoginAPIView,
    MeAPIView,
    MeSkillsAPIView,
    OnboardingAPIView,
    PasswordChangeAPIView,
    PasswordForgotAPIView,
    PasswordResetAPIView,
    RegisterAPIView,
    SafeTokenRefreshView,
    LogoutAPIView,
    UsernameAvailabilityAPIView,
    SkillListAPIView,
    SuggestedUsersAPIView,
    UserDetailAPIView,
    UserListAPIView,
    UserPortfolioAPIView,
)

urlpatterns = [
    path("auth/register/", RegisterAPIView.as_view(), name="auth-register"),
    path("auth/login/", LoginAPIView.as_view(), name="auth-login"),
    path("auth/refresh/", SafeTokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("auth/me/", MeAPIView.as_view(), name="auth-me"),
    path("auth/me/skills/", MeSkillsAPIView.as_view(), name="auth-me-skills"),
    path("auth/password/change/", PasswordChangeAPIView.as_view(), name="auth-password-change"),
    path("auth/username-available/", UsernameAvailabilityAPIView.as_view(), name="auth-username-available"),
    path("auth/password/forgot/", PasswordForgotAPIView.as_view(), name="auth-password-forgot"),
    path("auth/password/reset/", PasswordResetAPIView.as_view(), name="auth-password-reset"),
    path("auth/onboarding/", OnboardingAPIView.as_view(), name="auth-onboarding"),
    path("users/", UserListAPIView.as_view(), name="user-list"),
    path("users/suggested/", SuggestedUsersAPIView.as_view(), name="user-suggested"),
    path("users/<str:username>/connect/", ConnectionAPIView.as_view(), name="user-connect"),
    path("users/<str:username>/portfolio/", UserPortfolioAPIView.as_view(), name="user-portfolio"),
    path("users/<str:username>/", UserDetailAPIView.as_view(), name="user-detail"),
    path("skills/", SkillListAPIView.as_view(), name="skill-list"),
    path("admin/stats/", AdminStatsAPIView.as_view(), name="admin-stats"),
    path("admin/users/", AdminUserListAPIView.as_view(), name="admin-user-list"),
    path("admin/users/<int:id>/", AdminUserDetailAPIView.as_view(), name="admin-user-detail"),
    path("admin/books/", AdminBookListCreateAPIView.as_view(), name="admin-book-list"),
    path("admin/books/<int:id>/", AdminBookDetailAPIView.as_view(), name="admin-book-detail"),
    path("admin/books/<int:id>/chapters/", AdminBookChaptersAPIView.as_view(), name="admin-book-chapters"),
    path("admin/chapters/<int:id>/", AdminChapterDetailAPIView.as_view(), name="admin-chapter-detail"),
    path("admin/projects/", AdminProjectListAPIView.as_view(), name="admin-project-list"),
    path("admin/projects/<slug:slug>/", AdminProjectDetailAPIView.as_view(), name="admin-project-detail"),
    path("admin/reports/", AdminReportsAPIView.as_view(), name="admin-reports"),
    path("admin/reports/<int:id>/", AdminReportDetailAPIView.as_view(), name="admin-report-detail"),
]
