# Generated by Django 4.2.30 on 2026-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='est_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='book_completion_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='completed_chapters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
