# Generated by Django 4.2.30 on 2026-09-18 23:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_est_minutes_book_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/', validators=[core.validators.validate_cover_upload]),
        ),
    ]
