# Generated by Django 4.2.30 on 2026-09-18 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('criteria_key', models.CharField(max_length=100)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='award', max_length=50)),
            ],
            options={
                'ordering': ['-xp_reward', 'name'],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['slug'], name='gamificatio_slug_e8a164_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['criteria_key', 'xp_reward'], name='gamificatio_criteri_e9cf67_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['created_at'], name='gamificatio_created_a60165_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_a78f12_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['source', 'amount'], name='gamificatio_source_756109_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'badge'], name='gamificatio_user_id_2146ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['created_at'], name='gamificatio_created_56df8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
