create function public.colearn_badges() returns jsonb language sql stable security definer set search_path='' as $$
select jsonb_build_object('earned',coalesce(jsonb_agg(to_jsonb(b)||jsonb_build_object('earned_at',ub.earned_at,'progress',app.badge_progress(auth.uid(),b.criteria_key))) filter(where ub.id is not null),'[]'),'locked',coalesce(jsonb_agg(to_jsonb(b)||jsonb_build_object('progress',app.badge_progress(auth.uid(),b.criteria_key))) filter(where ub.id is null),'[]')) from public.badges b left join public.user_badges ub on ub.badge_id=b.id and ub.user_id=auth.uid() where app.active() $$;
create function public.colearn_leaderboard(period text default 'all',role_filter text default '',row_limit integer default 50) returns jsonb language sql stable security definer set search_path='' as $$
with scores as(select p,case when period='all' then p.xp else coalesce((select sum(amount) from public.xp_events where user_id=p.id and created_at>=case period when 'week' then now()-interval '7 days' else now()-interval '30 days' end),0) end as score from public.profiles p where p.is_active and (role_filter='' or p.role=role_filter) and app.active()), ranked as(select *,row_number() over(order by score desc,(p).created_at) rank from scores) select coalesce(jsonb_agg(jsonb_build_object('rank',rank,'xp',score,'self',(p).id=auth.uid(),'user',to_jsonb(p)||jsonb_build_object('badge_count',(select count(*) from public.user_badges where user_id=(p).id))) order by rank),'[]') from ranked where rank<=least(greatest(row_limit,1),100) or (p).id=auth.uid() $$;
create function public.colearn_portfolio(username text) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare p public.profiles;begin
 select * into p from public.profiles where profiles.username=colearn_portfolio.username and is_active;
 if p.id is null then raise exception 'Profile not found';end if;
 return jsonb_build_object('profile',to_jsonb(p),
 'skills',coalesce((select jsonb_agg(to_jsonb(s)||jsonb_build_object('level',us.level,'is_verified',us.is_verified)) from public.user_skills us join public.skills s on s.id=us.skill_id where us.user_id=p.id),'[]'),
 'projects',coalesce((select jsonb_agg(jsonb_build_object('id',pr.id,'slug',pr.slug,'title',pr.title,'summary',pr.summary,'status',pr.status,'tech_stack',pr.tech_stack,'role',m.role)) from public.projects pr join public.project_members m on m.project_id=pr.id where m.user_id=p.id and pr.is_public),'[]'),
 'badges',coalesce((select jsonb_agg(to_jsonb(b)||jsonb_build_object('earned_at',ub.earned_at)) from public.user_badges ub join public.badges b on b.id=ub.badge_id where ub.user_id=p.id),'[]'),
 'books',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'slug',b.slug,'title',b.title,'category',b.category,'cover',b.cover,'completed_at',r.updated_at)) from public.reading_progress r join public.books b on b.id=r.book_id where r.user_id=p.id and r.completed),'[]'),
 'heatmap',coalesce((select jsonb_agg(x) from (select d::date date,(select count(*) from public.xp_events e where e.user_id=p.id and e.created_at::date=d::date) count from generate_series(current_date-83,current_date,interval '1 day') d) x),'[]'),
 'stats',jsonb_build_object('xp',p.xp,'level',p.level,'streak_days',p.streak_days,'projects',(select count(*) from public.project_members m join public.projects pr on pr.id=m.project_id where m.user_id=p.id and pr.is_public),'books_completed',(select count(*) from public.reading_progress where user_id=p.id and completed),'badges',(select count(*) from public.user_badges where user_id=p.id)));
 end $$;
create function public.colearn_admin_stats() returns jsonb language plpgsql stable security definer set search_path='' as $$ begin
 if not app.staff() then raise exception 'Staff required' using errcode='42501';end if;
 return jsonb_build_object('totals',jsonb_build_object('users',(select count(*) from public.profiles),'books',(select count(*) from public.books),'projects',(select count(*) from public.projects),'threads',(select count(*) from public.threads),'reports',(select count(*) from public.reports)),
 'signups_30d',(select count(*) from public.profiles where created_at>now()-interval '30 days'),'signups_7d',(select count(*) from public.profiles where created_at>now()-interval '7 days'),'active_projects',(select count(*) from public.projects where status='active'),'books_added_30d',(select count(*) from public.books where created_at>now()-interval '30 days'),'open_reports',(select count(*) from public.reports where status in ('open','review')),'xp_awarded_30d',(select coalesce(sum(amount),0) from public.xp_events where created_at>now()-interval '30 days'),
 'daily',(select jsonb_agg(x) from(select d::date date,(select count(*) from public.profiles where created_at::date=d::date) signups,(select count(*) from public.projects where created_at::date=d::date) projects from generate_series(current_date-29,current_date,interval '1 day')d)x),'signals',jsonb_build_object('pending_requests',(select count(*) from public.join_requests where status='pending'),'unresolved_contacts',(select count(*) from public.contact_messages where not is_resolved)),'top_books',coalesce((select jsonb_agg(x) from(select b.id,b.title,b.slug,count(r.id) readers from public.books b left join public.reading_progress r on r.book_id=b.id group by b.id order by count(r.id) desc limit 5)x),'[]'));
end $$;
create function public.colearn_reports(status_filter text default '') returns jsonb language plpgsql stable security definer set search_path='' as $$ begin
 if not app.staff() then raise exception 'Staff required' using errcode='42501';end if;
 return coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('reporter',to_jsonb(p),'target',jsonb_build_object('type',r.target_type,'id',coalesce(r.thread_id::text,r.comment_id::text,r.target_user_id::text),'exists',coalesce(t.id::text,c.id::text,u.id::text) is not null,'label',coalesce(t.title,c.body,u.username,'Deleted content'),'slug',coalesce(t.slug,ct.slug,''),'username',u.username,'preview',coalesce(t.body,c.body,''),'author',coalesce(ta.username,ca.username,u.username,''))) order by r.created_at desc) from public.reports r join public.profiles p on p.id=r.reporter_id left join public.threads t on t.id=r.thread_id left join public.comments c on c.id=r.comment_id left join public.threads ct on ct.id=c.thread_id left join public.profiles u on u.id=r.target_user_id left join public.profiles ta on ta.id=t.author_id left join public.profiles ca on ca.id=c.author_id where status_filter='' or r.status=status_filter or (status_filter='pending' and r.status in ('open','review'))),'[]');end $$;
create function public.colearn_moderate(report_id bigint,action text) returns jsonb language plpgsql security definer set search_path='' as $$ declare r public.reports;u uuid;begin
 if not app.staff() then raise exception 'Staff required' using errcode='42501';end if;select * into r from public.reports where id=report_id for update;if r.id is null then raise exception 'Report not found';end if;
 if action='remove_content' then delete from public.threads where id=r.thread_id;delete from public.comments where id=r.comment_id;
 elsif action='deactivate_user' then u=coalesce(r.target_user_id,(select author_id from public.threads where id=r.thread_id),(select author_id from public.comments where id=r.comment_id));if u=auth.uid() or exists(select 1 from public.profiles where id=u and is_staff) then raise exception 'Cannot deactivate staff';end if;update public.profiles set is_active=false where id=u;
 elsif action not in ('review','resolve','dismiss','reopen') then raise exception 'Invalid moderation action';end if;
 update public.reports set status=case action when 'review' then 'review' when 'dismiss' then 'dismissed' when 'reopen' then 'open' else 'resolved' end where id=report_id;return (select value from jsonb_array_elements(public.colearn_reports('')) where (value->>'id')::bigint=report_id);end $$;
revoke all on function public.colearn_badges(),public.colearn_leaderboard(text,text,integer),public.colearn_admin_stats(),public.colearn_reports(text),public.colearn_moderate(bigint,text) from public,anon;
grant execute on function public.colearn_badges(),public.colearn_leaderboard(text,text,integer),public.colearn_admin_stats(),public.colearn_reports(text),public.colearn_moderate(bigint,text) to authenticated;
revoke all on function public.colearn_portfolio(text) from public;
grant execute on function public.colearn_portfolio(text) to anon,authenticated;
-- Service-only auth migration bridge: hashes never enter the browser or public API.
create table app.legacy_auth(user_id uuid primary key references auth.users on delete cascade,password_hash text not null);
create function public.colearn_legacy_hash(email_address text) returns jsonb language sql security definer set search_path='' as $$ select jsonb_build_object('id',u.id,'hash',l.password_hash) from auth.users u join app.legacy_auth l on l.user_id=u.id where lower(u.email)=lower(email_address) $$;
create function public.colearn_clear_legacy(user_uuid uuid) returns void language sql security definer set search_path='' as $$ delete from app.legacy_auth where user_id=user_uuid $$;
create function public.colearn_contact(data jsonb,client_hash text) returns void language plpgsql security definer set search_path='' as $$ begin
 perform pg_advisory_xact_lock(hashtextextended(client_hash,0));if (select count(*) from public.contact_messages where ip_hash=client_hash and created_at>now()-interval '1 hour')>=10 then raise exception 'Too many requests. Please try again later.';end if;
 insert into public.contact_messages(name,email,subject,message,ip_hash) values(data->>'name',data->>'email',data->>'subject',data->>'message',client_hash);end $$;
revoke all on function public.colearn_legacy_hash(text),public.colearn_clear_legacy(uuid),public.colearn_contact(jsonb,text) from public,anon,authenticated;
grant execute on function public.colearn_legacy_hash(text),public.colearn_clear_legacy(uuid),public.colearn_contact(jsonb,text) to service_role;
-- Storage. Private project covers inherit project visibility; no public URL can bypass it.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('avatars','avatars',true,2097152,array['image/jpeg','image/png','image/webp']),
 ('book-covers','book-covers',true,5242880,array['image/jpeg','image/png','image/webp']),
 ('project-covers','project-covers',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy media_read on storage.objects for select to authenticated using((bucket_id in ('avatars','book-covers') and app.active()) or (bucket_id='project-covers' and exists(select 1 from public.projects where id::text=(storage.foldername(name))[1] and app.visible(id))));
create policy media_insert on storage.objects for insert to authenticated with check(app.active() and ((bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) or (bucket_id='book-covers' and app.staff()) or (bucket_id='project-covers' and exists(select 1 from public.projects where id::text=(storage.foldername(name))[1] and (app.owner(id) or app.staff())))));
create policy media_delete on storage.objects for delete to authenticated using(app.active() and ((bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) or (bucket_id='book-covers' and app.staff()) or (bucket_id='project-covers' and exists(select 1 from public.projects where id::text=(storage.foldername(name))[1] and (app.owner(id) or app.staff())))));
