# Generated by Django 4.2.30 on 2026-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connection_skill_userskill_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
