# Generated by Django 4.2.30 on 2026-09-18 23:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_interests_customuser_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[core.validators.validate_avatar_upload]),
        ),
    ]
