# Generated by Django 4.2.30 on 2026-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('review', 'Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
    ]
